apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: play-java-docker-k8s-starter-example
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: play-java-docker-k8s-example
        type: play-java-docker-k8s-starter-example
    spec:
      containers:
      - name: play-java-docker-k8s-example
        image: samplegroup/play-java-docker-k8s-starter-example
        imagePullPolicy: Never
        ports:
        - containerPort: 9000  # The kubectl proxy will default to the first port in the list
          name: play-http
        resources:
          limits:
            cpu: 250m
            memory: 384Mi
          requests:
            cpu: 250m
            memory: 384Mi
        env:
        - name: POD_IP
          valueFrom:
            fieldRef:
              fieldPath: status.podIP
        readinessProbe:
          httpGet:
            path: /
            port: 9000
          initialDelaySeconds: 30
          timeoutSeconds: 30
